In [1]:
import numpy as np

**Задание 1**

**1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно**

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

**2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.**

In [14]:
a1 = a.reshape(12, 1)
a1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [8]:
a2 = a.reshape(2, 6)
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a3 = a.reshape(3, 4)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a4 = a.reshape(4, 3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
a5 = a.reshape(6, 2)
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

**3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).**

In [21]:
a_1 = a.reshape(-1, 1)
a_1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [24]:
a_2 = a.reshape(-1, 6)
a_2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
a_3 = a.reshape(-1, 4)
a_3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a_4 = a.reshape(4, -1)
a_4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [27]:
a_5 = a.reshape(6, -1)
a_5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

**4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?**

Да, можем. Т.к. для обращения к любому элементу массива нам нужно использовать только один индекс. Например:

In [33]:
a_1[10]

array([22])

**5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.**

In [35]:
e = np.random.randn(3, 4)
e

array([[-0.13388732,  0.07046982,  1.51423885, -0.85033681],
       [ 0.38761974, -1.7070617 , -1.15876571, -1.79188117],
       [ 0.78726782,  0.14532841,  0.94613419,  1.45656876]])

In [38]:
f = e.flatten()
f

array([-0.13388732,  0.07046982,  1.51423885, -0.85033681,  0.38761974,
       -1.7070617 , -1.15876571, -1.79188117,  0.78726782,  0.14532841,
        0.94613419,  1.45656876])

In [39]:
e.size == f.size

True

**6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?**

In [40]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [47]:
b = np.arange(20, 1, -2).reshape(1, -1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [52]:
a.ndim == b.ndim

False

In [58]:
a.shape == b.shape

False

Массив "а" у нас одномерный, а массив "b" - двухмерный, у него есть оси и другая размерность.

**7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.**

In [68]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [69]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [71]:
d = np.concatenate((a, b))
d

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
c.size & d.size == 10

True

**8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?**

In [74]:
A = np.arange(12).reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [77]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [78]:
B.size

16

In [79]:
np.linalg.det(B)

0.0

Матрица B имеет размер 16 элементов.
Обратную матрицу вычислить не получится, т.к. определитель матрицы В равен нулю.

**9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.**

In [81]:
np.random.seed(42)

In [84]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [83]:
C = np.reshape(c, (4, 4))
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [87]:
D = (C * 10) + B
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [88]:
np.linalg.det(D)

5.18953807259442e-26

In [89]:
np.linalg.matrix_rank(D)

2

In [97]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

**10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы.
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.**

In [108]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.]])

In [109]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [110]:
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
E = np.where([D_inv], B, C)
E

array([[[  5,   1,   2,  32],
        [ 14,   5,  86,   7],
        [  8,  86,  10,  11],
        [ 32,  13, 212, 302]]])

**Задание 2**

**Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.**

In [123]:
a = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [124]:
mean_a = [a.mean(axis = 0)]
mean_a

[array([2. , 8.4])]

**Задание 3**

**Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.**

In [125]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 4**

**Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.**

In [126]:
a_centered[:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [128]:
a_centered[:, 1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [129]:
a_centered_sp = (a_centered[:, 0]) @ (a_centered[:, 1])
a_centered_sp

8.0

In [131]:
N = a.shape[0]

5

In [135]:
cov = a_centered_sp / (N - 1)
cov

2.0

**Задание 5**

**Число, которое мы получили в конце задания 4, является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 4 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.**

**В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.**

In [133]:
a = a.T
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [137]:
x_cov = np.cov(a)

In [140]:
cov == x_cov[0, 1]

True